In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1


#### **Creating tensors with torch.Tensor()**

In [12]:
# scalar
scalar = torch.tensor(3.14159)
print(scalar)
print(scalar.ndim)

# Retrieve Python int from tensor:
print(scalar.item())

tensor(3.1416)
0
3.141590118408203


In [15]:
# vector
vector = torch.tensor([1, 5])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([1, 5])
1
torch.Size([2])
1


In [17]:
# matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])

print(matrix.ndim)
print(matrix.shape)

2
torch.Size([2, 2])


In [22]:
# tensor
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

print(tensor.ndim)
print(tensor.shape)
print(tensor.size())


3
torch.Size([1, 3, 3])
torch.Size([1, 3, 3])


#### **Creating random tensor**
This is important for random weights initialization, for example.

In [25]:
# create random tensor of shape [3, 4]
random_tensor = torch.rand(3, 4)
print(random_tensor)
print(random_tensor.shape)
print(random_tensor.ndim)

tensor([[0.9933, 0.1576, 0.9539, 0.0947],
        [0.3397, 0.2283, 0.7663, 0.9738],
        [0.3791, 0.3068, 0.5882, 0.8549]])
torch.Size([3, 4])
2


#### **Random tensor following the format of an image**

In [29]:
random_tensor_image = torch.rand(size=(3, 256, 256))
random_tensor_image.shape, random_tensor_image.ndim

(torch.Size([3, 256, 256]), 3)

#### **Zeros and ones tensors**

In [31]:
zeros = torch.zeros(size=(3,4))

ones = torch.ones(size=(3,4))

zeros, ones

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

#### **Creating tensors in certain range**

In [33]:
one_to_ten = torch.arange(start=0, end=11, step=1)
print(one_to_ten)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


#### **Creating tensors like**
With this, we are able to create tensors that have the same shape than other tensors.

In [34]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### **Torch data type:**
The default datatype of pytorch is float32 (rarely int64). We can change it.

In [44]:
float_32_tensor = torch.tensor([3.0, 5.7, 9])
print(float_32_tensor.dtype)
int_64_tensor = torch.tensor([3, 5, 9])
print(int_64_tensor.dtype)

# Changing dtype:
float_16_tensor = torch.tensor([3, 5, 6],
                           dtype = torch.float16)
print(float_16_tensor.dtype)

# The following fails to change the dtype!
none_tensor = torch.tensor([3, 5, 6],
                           dtype = None)
print(none_tensor.dtype)

example_tensor = torch.tensor([2, 5, 6],
                              dtype=None,  # what datatype is the tensor (e.g float32, float16)
                              device=None, # 
                              requires_grad=False)
print(example_tensor.dtype)

torch.float32
torch.int64
torch.float16
torch.int64
torch.int64
