In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1


#### **Creating tensors with torch.Tensor()**

In [2]:
# scalar
scalar = torch.tensor(3.14159)
print(scalar)
print(scalar.ndim)

# Retrieve Python int from tensor:
print(scalar.item())

tensor(3.1416)
0
3.141590118408203


In [3]:
# vector
vector = torch.tensor([1, 5])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([1, 5])
1
torch.Size([2])


In [4]:
# matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])

print(matrix.ndim)
print(matrix.shape)

2
torch.Size([2, 2])


In [5]:
# tensor
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

print(tensor.ndim)
print(tensor.shape)
print(tensor.size())


3
torch.Size([1, 3, 3])
torch.Size([1, 3, 3])


#### **Creating random tensor**
This is important for random weights initialization, for example.

In [6]:
# create random tensor of shape [3, 4]
random_tensor = torch.rand(3, 4)
print(random_tensor)
print(random_tensor.shape)
print(random_tensor.ndim)

tensor([[0.9711, 0.7796, 0.2164, 0.8871],
        [0.9174, 0.1500, 0.3275, 0.8811],
        [0.6086, 0.4280, 0.8454, 0.4043]])
torch.Size([3, 4])
2


#### **Random tensor following the format of an image**

In [7]:
random_tensor_image = torch.rand(size=(3, 256, 256))
random_tensor_image.shape, random_tensor_image.ndim

(torch.Size([3, 256, 256]), 3)

#### **Zeros and ones tensors**

In [8]:
zeros = torch.zeros(size=(3,4))

ones = torch.ones(size=(3,4))

zeros, ones

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

#### **Creating tensors in certain range**

In [9]:
one_to_ten = torch.arange(start=0, end=11, step=1)
print(one_to_ten)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


#### **Creating tensors like**
With this, we are able to create tensors that have the same shape than other tensors.

In [10]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### **Torch data type:**
The default datatype of pytorch is float32 (rarely int64). We can change it.
**Note:** Tensors datatypes is one of the most common errors you'll run into with Pytorch and Deep Learning code.

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [11]:
float_32_tensor = torch.tensor([3.0, 5.7, 9])
print(float_32_tensor.dtype)
int_64_tensor = torch.tensor([3, 5, 9])
print(int_64_tensor.dtype)

# Changing dtype:
float_16_tensor = torch.tensor([3, 5, 6],
                           dtype = torch.float16)
print(float_16_tensor.dtype)
# or:

float_16_tensor = float_32_tensor.type(torch.float16)
print(float_16_tensor.dtype)
# The following fails to change the dtype!
none_tensor = torch.tensor([3, 5, 6],
                           dtype = None)
print(none_tensor.dtype)

example_tensor = torch.tensor([2, 5, 6],
                              dtype=None,  # what datatype is the tensor (e.g float32, float16)
                              device=None, # 
                              requires_grad=False)
print(example_tensor.dtype)

torch.float32
torch.int64
torch.float16
torch.float16
torch.int64
torch.int64


**More about item 3:** 

When you try to compute operations between a tensor that is running on a device (e.g GPU) and a tensor that is running on another device (e.g CPU), Pytorch throws you an error.

**The field** `requires_grad` is if you want Pytorch to track the gradients of this tensor. (Weight matrices in a NN). 

#### **Getting important information from tensors**

1. `tensor.dtype`
2. `tensor.shape`
3. `tensor.device`

In [12]:
# Create a tensor
some_tensor = torch.rand(size=(4,4))

# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}\nShape of tensor: {some_tensor.shape}\nDevice of tensor: {some_tensor.device}")

tensor([[0.8432, 0.8283, 0.2404, 0.7803],
        [0.0733, 0.1817, 0.3027, 0.0931],
        [0.8981, 0.9237, 0.0486, 0.6213],
        [0.0448, 0.6768, 0.4952, 0.0245]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([4, 4])
Device of tensor: cpu


### **Manipulating Tensors (tensor operations)**
Tensor operations include:
 * Addition
 * Subtraction
 * Multiplication (element-wise)
 * Division
 * Matrix multiplication

#### **Operations with scalars:**

In [13]:
tensor = torch.tensor([1, 2, 3])
print(tensor + 1)
print(tensor - 1)
print(tensor**2)
print(tensor * 10)
print(tensor/2)

tensor([2, 3, 4])
tensor([0, 1, 2])
tensor([1, 4, 9])
tensor([10, 20, 30])
tensor([0.5000, 1.0000, 1.5000])


#### **Operations with tensors (element - wise)**

In [14]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([2, 1, 1])
print(tensor1 + tensor2)
print(tensor1 - tensor2)
print(tensor**tensor2)
print(tensor1*tensor2)
print(tensor/tensor2)

tensor([3, 3, 4])
tensor([-1,  1,  2])
tensor([1, 2, 3])
tensor([2, 2, 3])
tensor([0.5000, 2.0000, 3.0000])


#### **Matrix Multiplication (dot product of rows and columns)**

In [15]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([2, 1, 1])
print(torch.matmul(tensor1, tensor2))

tensor(7)


Let's look at the difference in time taken to matmul with Pytorch vs plain Python:

In [16]:
%%time
value = 0
for i in range(len(tensor1)):
    value += tensor1[i]*tensor2[i]
print(value)

tensor(7)
CPU times: user 1.15 ms, sys: 3.63 ms, total: 4.79 ms
Wall time: 3.52 ms


In [17]:
%%time
print(torch.matmul(tensor1, tensor2))

tensor(7)
CPU times: user 3.6 ms, sys: 0 ns, total: 3.6 ms
Wall time: 2.46 ms


Remember that in order to multiply tensors, we need to repect one main rule:
1. the dimensions of the matrices must match. (i.e the number of columns of the first matrix must be equal to the number of rows of the second matrix)

Also, the resulting matrix will have the following shape: `number of rows of the first matrix X number of columns of the second matrix`

#### **Transposing Tensors:**
I think this can be called one of the fundamental mathematical thecniques applied to machine learning in general. Considering that most of ML is built upon the following linear equation:
$$
f({\bf x}) = w_0 + w_1x_1 + \ldots + w_dx_d
$$

The matrix multiplication ${\bf wx}$ is not possible because of the differences in shapes. But, using the transpose, we can write:
$$
f({\bf x}) = {\bf w}^{\bf T}{\bf x}
$$

In [18]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

result = torch.matmul(tensor_A,tensor_B.T)
result

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [19]:
tensor_B, tensor_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([3, 2]))

In [20]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

#### **Aggregation functions in tensors**
- min
- max
- mean
- sum
- $\vdots$ 

In [ ]:
tensor_A = torch.tensor([[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12], 
                         [13, 14, 15, 16]])

In [21]:
# Find the min:
torch.min(tensor_A), tensor_A.min()

tensor(1)


In [22]:
# Find the max
torch.max(tensor_A), tensor_A.max()

tensor(6)

In [24]:
# Find the mean - note: the torch.mean() function requires a tensor of dtype: float32
torch.mean(tensor_A.type(torch.float32)), tensor_A.type(torch.float32).mean()

(tensor(3.5000), tensor(3.5000))

In [25]:
# Find the sum
torch.sum(tensor_A), tensor_A.sum()

(tensor(21), tensor(21))

### **Finding** `argmax{`**x**`}` and `argmin{`**x**`}`

In [28]:
x = torch.tensor([1, 2, 3])

In [29]:
torch.argmax(x), torch.argmin(x)

(tensor(2), tensor(0))

In [30]:
x[torch.argmax(x)], x[torch.argmin(x)]

(tensor(3), tensor(1))

### **Reshaping, stacking, squeezing and unsqueezing tensors**
- Reshaping - reshapes an input tensor to a defined shape
- View - returns a view of an input tensor but attaches the same place in memory to the both references
- Stacking - combines multiple tensors on top of each other (vstack) or side by side (hstack)
- Squeeze - removes all `1` (redundant) dimensions from a tensor
- Unsqueeze - adds a `1` diension to a target tensor
- Permute - returns a view of the input with dimensions permutes (swapped) in a certain way


In [32]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

##### **Reshape**

In [34]:
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

##### **View**

In [35]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [36]:
z[:, 0] = 5  # changes the first element in z to 5
z, x  # changes the first element in x to 5 as well

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))