In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1


#### **Creating tensors with torch.Tensor()**

In [3]:
# scalar
scalar = torch.tensor(3.14159)
print(scalar)
print(scalar.ndim)

# Retrieve Python int from tensor:
print(scalar.item())

tensor(3.1416)
0
3.141590118408203


In [4]:
# vector
vector = torch.tensor([1, 5])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([1, 5])
1
torch.Size([2])


In [5]:
# matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])

print(matrix.ndim)
print(matrix.shape)

2
torch.Size([2, 2])


In [6]:
# tensor
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

print(tensor.ndim)
print(tensor.shape)
print(tensor.size())


3
torch.Size([1, 3, 3])
torch.Size([1, 3, 3])


#### **Creating random tensor**
This is important for random weights initialization, for example.

In [7]:
# create random tensor of shape [3, 4]
random_tensor = torch.rand(3, 4)
print(random_tensor)
print(random_tensor.shape)
print(random_tensor.ndim)

tensor([[0.0833, 0.7397, 0.4310, 0.4233],
        [0.1110, 0.5024, 0.0225, 0.8073],
        [0.8224, 0.0529, 0.8095, 0.0207]])
torch.Size([3, 4])
2


#### **Random tensor following the format of an image**

In [9]:
random_tensor_image = torch.rand(size=(3, 256, 256))
random_tensor_image.shape, random_tensor_image.ndim

(torch.Size([3, 256, 256]), 3)

#### **Zeros and ones tensors**

In [31]:
zeros = torch.zeros(size=(3,4))

ones = torch.ones(size=(3,4))

zeros, ones

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

#### **Creating tensors in certain range**

In [33]:
one_to_ten = torch.arange(start=0, end=11, step=1)
print(one_to_ten)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


#### **Creating tensors like**
With this, we are able to create tensors that have the same shape than other tensors.

In [34]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### **Torch data type:**
The default datatype of pytorch is float32 (rarely int64). We can change it.
**Note:** Tensors datatypes is one of the most common errors you'll run into with Pytorch and Deep Learning code.

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [10]:
float_32_tensor = torch.tensor([3.0, 5.7, 9])
print(float_32_tensor.dtype)
int_64_tensor = torch.tensor([3, 5, 9])
print(int_64_tensor.dtype)

# Changing dtype:
float_16_tensor = torch.tensor([3, 5, 6],
                           dtype = torch.float16)
print(float_16_tensor.dtype)
# or:

float_16_tensor = float_32_tensor.type(torch.float16)
print(float_16_tensor.dtype)
# The following fails to change the dtype!
none_tensor = torch.tensor([3, 5, 6],
                           dtype = None)
print(none_tensor.dtype)

example_tensor = torch.tensor([2, 5, 6],
                              dtype=None,  # what datatype is the tensor (e.g float32, float16)
                              device=None, # 
                              requires_grad=False)
print(example_tensor.dtype)

torch.float32
torch.int64
torch.float16
torch.float16
torch.int64
torch.int64


**More about item 3:** 

When you try to compute operations between a tensor that is running on a device (e.g GPU) and a tensor that is running on another device (e.g CPU), Pytorch throws you an error.

**The field** `requires_grad` is if you want Pytorch to track the gradients of this tensor. (Weight matrices in a NN). 

#### **Getting important information from tensors**

1. `tensor.dtype`
2. `tensor.shape`
3. `tensor.device`

In [12]:
# Create a tensor
some_tensor = torch.rand(size=(4,4))

# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}\nShape of tensor: {some_tensor.shape}\nDevice of tensor: {some_tensor.device}")

tensor([[0.8670, 0.0928, 0.7413, 0.1879],
        [0.5399, 0.1544, 0.4794, 0.0671],
        [0.2780, 0.6215, 0.2664, 0.7347],
        [0.6546, 0.6626, 0.0857, 0.3111]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([4, 4])
Device of tensor: cpu


### **Manipulating Tensors (tensor operations)**
Tensor operations include:
 * Addition
 * Subtraction
 * Multiplication (element-wise)
 * Division
 * Matrix multiplication

#### **Operations with scalars:**

In [16]:
tensor = torch.tensor([1, 2, 3])
print(tensor + 1)
print(tensor - 1)
print(tensor**2)
print(tensor * 10)
print(tensor/2)

tensor([2, 3, 4])
tensor([0, 1, 2])
tensor([1, 4, 9])
tensor([10, 20, 30])
tensor([0.5000, 1.0000, 1.5000])


#### **Operations with tensors (element - wise)**

In [21]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([2, 1, 1])
print(tensor1 + tensor2)
print(tensor1 - tensor2)
print(tensor**tensor2)
print(tensor1*tensor2)
print(tensor/tensor2)

tensor([3, 3, 4])
tensor([-1,  1,  2])
tensor([1, 2, 3])
tensor([2, 2, 3])
tensor([0.5000, 2.0000, 3.0000])


#### **Matrix Multiplication (dot product of rows and columns)**

In [22]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([2, 1, 1])
print(torch.matmul(tensor1, tensor2))

tensor(7)


Let's look at the difference in time taken to matmul with Pytorch vs plain Python:

In [23]:
%%time
value = 0
for i in range(len(tensor1)):
    value += tensor1[i]*tensor2[i]
print(value)

tensor(7)
CPU times: user 2.15 ms, sys: 245 µs, total: 2.39 ms
Wall time: 6.48 ms


In [24]:
%%time
print(torch.matmul(tensor1, tensor2))

tensor(7)
CPU times: user 853 µs, sys: 97 µs, total: 950 µs
Wall time: 761 µs
